inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks
  - utils:fix

mypy:
  options:
    python-version: "3.10"

ruff:
  options:
    target-version: py310
pycodestyle:
  disable:
    - N817 # camelcase, in conflict with Ruff about xml.etree.ElementTree
