inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks

doc-warnings: true

bandit:
  options:
    config: .bandit.yaml

pydocstyle:
  disable:
    - D417 # Missing argument descriptions in the docstring
